apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web-deployment
  labels:
    app: apache
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-web
        image: amemanagement/mike_apache_image:v1.0.1
        ports:
        - containerPort: 80